import { describe, it, expect } from 'vitest';

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

import { buildPlanQr } from '../src/lib/qr/planQr.js';
import { toKeyIdHex } from '../src/lib/qr/envelope.js';
import { renderSheetCodes } from '../src/lib/sheet/planSheet.js';
import PlanSheet from '../src/components/PlanSheet.jsx';

/* This test has a side effect on purpose: it writes `docs/sample-plan-sheet.html`.
 *
 * The only thing still standing between the return channel and a real
 * walkthrough is physical -- the sheet has never been through the printer and
 * no phone has scanned it off paper -- and that test can only be run by the
 * owner, at the printer. Requiring him to start the admin app, paste a payload
 * and issue a plan first is friction that has kept it undone for two days.
 *
 * So the printable sample is a build product of `npm test`: always rendered
 * from the current component and CSS, never a stale hand-made copy. Open the
 * file in a browser, print it, scan it. The codes are real -- built from the
 * shipped sample payload with a freshly minted key -- so a phone that scans
 * them lands on a genuine /pair and /plan. The key is NOT recorded in any
 * issued-key store, which is correct for a sample: nothing should ever be able
 * to open a "return" for Maria Santos. */

const BASE = 'https://cadence.example.com';
const SAMPLE = JSON.parse(
  readFileSync(fileURLToPath(new URL('../docs/sample-plan-payload.json', import.meta.url)), 'utf8'),
);
const APP_CSS = readFileSync(fileURLToPath(new URL('../src/styles/app.css', import.meta.url)), 'utf8');
const OUT = fileURLToPath(new URL('../docs/sample-plan-sheet.html', import.meta.url));

/* Only the sheet's own rules, plus the print rules. Pulling in the whole app
 * stylesheet would drag the admin chrome's theme variables onto paper. */
function sheetCss() {
  const start = APP_CSS.indexOf('/* ---- The printed companion sheet (1f)');
  if (start === -1) throw new Error('sheet CSS block not found in app.css');
  return APP_CSS.slice(start);
}

/* Fixed key and IV, so the committed file is byte-stable.
 *
 * The first version minted a fresh key on every run, which meant every
 * `npm test` -- including the one inside STATUS.md's regeneration -- rewrote
 * the two QR codes and left docs/sample-plan-sheet.html dirty on whichever
 * machine ran it. A sample that opens nothing anywhere (fake employee, fake
 * host, key recorded in no issued-key store) loses nothing by having a public
 * key; it gains a file that only changes when the sheet itself changes, which
 * is exactly the diff worth seeing. */
const SAMPLE_KEY = Uint8Array.from({ length: 32 }, (_, i) => (i * 7 + 3) & 0xff);
const SAMPLE_IV = Uint8Array.from({ length: 12 }, (_, i) => (i * 13 + 5) & 0xff);

async function renderSample() {
  const payload = structuredClone(SAMPLE);
  const issued = await buildPlanQr(payload, { baseUrl: BASE, iv: SAMPLE_IV, rawKey: SAMPLE_KEY });
  const codes = await renderSheetCodes(issued);
  const body = renderToStaticMarkup(
    createElement(PlanSheet, { payload, codes, issued, keyIdHex: toKeyIdHex(issued.keyId) }),
  );
  return { html: [
    '<!doctype html>',
    '<html lang="en"><head><meta charset="utf-8">',
    '<title>HMA Cadence — sample plan sheet (print test)</title>',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<style>${sheetCss()}</style>`,
    '</head><body>',
    '<!-- Generated by test/planSheetSample.test.js. Do not edit; run npm test. -->',
    body,
    '</body></html>',
  ].join('\n'), codes, issued };
}

describe('the printable sample sheet', () => {
  it('is written to docs/ so the owner can print it without the admin app', async () => {
    const { html, codes } = await renderSample();

    mkdirSync(fileURLToPath(new URL('../docs/', import.meta.url)), { recursive: true });
    // Normalised to LF. The sheet embeds app.css and is built from template
    // literals in sources git checks out as CRLF on Windows, so the generated
    // bytes were platform-dependent: every `npm test` on Windows left the
    // committed file modified, with `git diff` showing nothing and `git status`
    // showing a change. A permanently dirty tree trains people to stop reading
    // `git status`, which this estate depends on before staging.
    writeFileSync(OUT, html.replace(/\r\n/g, '\n'), 'utf8');

    const written = readFileSync(OUT, 'utf8');
    expect(written).not.toContain('\r');
    expect(written).toContain('plan-sheet');
    expect(written).toContain('@page');
    expect(written).toContain('110mm');
    expect(written.match(/<svg/g) ?? []).toHaveLength(2);
    expect(codes.readable).toBe(true);
  });

  it('is byte-stable across runs, so npm test never dirties the committed file', async () => {
    const first = (await renderSample()).html;
    const second = (await renderSample()).html;
    expect(second).toBe(first);
  });

  it('is byte-stable across PLATFORMS too, which is what actually dirtied it', async () => {
    // Stability within one machine was already asserted above, and was not
    // enough: run-to-run bytes were identical while the committed file went
    // modified on every run anyway, because the endings depended on how git
    // had checked out the sources this is built from. The test above claimed
    // more in its name than it checked.
    const { html } = await renderSample();
    expect(html.replace(/\r\n/g, '\n')).not.toContain('\r');
  });

  it('carries no admin-only styling, only the sheet and print rules', async () => {
    const { html } = await renderSample();

    expect(html).not.toContain('.import-editor');
    expect(html).not.toContain('.scan-reticle');
    expect(html).toContain('.plan-sheet__qr');
  });
});
