/**
 * QR envelope v1 — encode/decode for the Tracker → Cadence handoff.
 *
 * Spec: docs/qr-envelope.md. Both apps implement this independently, so treat
 * the byte layout here as frozen: any change needs a version bump and a matching
 * change in the Tracker.
 *
 * Everything is native WebCrypto + CompressionStream — no crypto or compression
 * library on either side. `encodePlanEnvelope` lives here (rather than only in
 * the Tracker) so the round-trip is testable in one place and so the committed
 * test vectors are generated by the same code that reads them.
 */

export const ENVELOPE_VERSION = 1;
export const KEY_BYTES = 32; // AES-256
export const KEY_ID_BYTES = 4;
export const IV_BYTES = 12; // 96-bit, the AES-GCM standard
const HEADER_BYTES = 1 + KEY_ID_BYTES + IV_BYTES;

/**
 * Anything malformed, unsupported, or undecryptable. `code` drives which screen
 * the employee sees — see the state table in docs/qr-envelope.md.
 *
 * Codes: 'malformed' | 'unsupported_version' | 'decrypt_failed'
 */
export class EnvelopeError extends Error {
  constructor(code, message) {
    super(message);
    this.name = 'EnvelopeError';
    this.code = code;
  }
}

// ── base64url (RFC 4648 §5) ──────────────────────────────────────────

export function toBase64Url(bytes) {
  let bin = '';
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

export function fromBase64Url(str) {
  if (typeof str !== 'string' || !/^[A-Za-z0-9_-]+$/.test(str)) {
    throw new EnvelopeError('malformed', 'Not valid base64url.');
  }
  const b64 = str.replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(str.length / 4) * 4, '=');
  let bin;
  try {
    bin = atob(b64);
  } catch {
    throw new EnvelopeError('malformed', 'Not valid base64url.');
  }
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

// ── raw DEFLATE ──────────────────────────────────────────────────────

async function pipe(bytes, stream) {
  const readable = new Blob([bytes]).stream().pipeThrough(stream);
  return new Uint8Array(await new Response(readable).arrayBuffer());
}

const deflateRaw = (bytes) => pipe(bytes, new CompressionStream('deflate-raw'));
const inflateRaw = (bytes) => pipe(bytes, new DecompressionStream('deflate-raw'));

// ── keys ─────────────────────────────────────────────────────────────

/** 32 random bytes from the OS CSPRNG. Not derived from anything. */
export function generatePlanKey() {
  return crypto.getRandomValues(new Uint8Array(KEY_BYTES));
}

/**
 * First 4 bytes of SHA-256(key). Not a security boundary — it only lets the
 * receiver distinguish "not my plan" from "corrupt data". A collision still
 * fails GCM authentication.
 */
export async function keyIdFor(rawKey) {
  const digest = await crypto.subtle.digest('SHA-256', rawKey);
  return new Uint8Array(digest, 0, KEY_ID_BYTES);
}

/**
 * Import raw key bytes as an AES-GCM CryptoKey.
 *
 * Cadence imports with extractable=false so no script on the phone can read the
 * bytes back out of IndexedDB. The Tracker needs extractable=true because it has
 * to render the key as a pairing QR.
 */
export async function importPlanKey(rawKey, { extractable = false } = {}) {
  if (!(rawKey instanceof Uint8Array) || rawKey.length !== KEY_BYTES) {
    throw new EnvelopeError('malformed', `Key must be ${KEY_BYTES} bytes.`);
  }
  return crypto.subtle.importKey('raw', rawKey, { name: 'AES-GCM' }, extractable, [
    'encrypt',
    'decrypt',
  ]);
}

// ── plan envelope ────────────────────────────────────────────────────

/**
 * payload → minify → deflate-raw → AES-GCM → [version|keyId|iv|ct] → base64url
 *
 * `iv` is injectable only so the committed test vectors are reproducible;
 * production callers must let it default to a fresh random value.
 */
export async function encodePlanEnvelope(payload, { key, keyId, iv } = {}) {
  const nonce = iv ?? crypto.getRandomValues(new Uint8Array(IV_BYTES));
  if (nonce.length !== IV_BYTES) throw new EnvelopeError('malformed', 'IV must be 12 bytes.');
  if (keyId?.length !== KEY_ID_BYTES) {
    throw new EnvelopeError('malformed', `keyId must be ${KEY_ID_BYTES} bytes.`);
  }

  const json = new TextEncoder().encode(JSON.stringify(payload));
  const compressed = await deflateRaw(json);
  const ct = new Uint8Array(
    await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, key, compressed),
  );

  const out = new Uint8Array(HEADER_BYTES + ct.length);
  out[0] = ENVELOPE_VERSION;
  out.set(keyId, 1);
  out.set(nonce, 1 + KEY_ID_BYTES);
  out.set(ct, HEADER_BYTES);
  return toBase64Url(out);
}

/**
 * Split the envelope without decrypting. Deliberately separate from
 * `decryptPlanEnvelope` — the receiver needs `keyId` to look up a key before it
 * can attempt decryption, and needs to hold the raw string as a pending plan
 * when no key is present yet.
 */
export function parsePlanEnvelope(encoded) {
  const bytes = fromBase64Url(encoded);
  if (bytes.length <= HEADER_BYTES) {
    throw new EnvelopeError('malformed', 'Envelope is too short.');
  }
  const version = bytes[0];
  if (version !== ENVELOPE_VERSION) {
    throw new EnvelopeError('unsupported_version', `Envelope version ${version} is not supported.`);
  }
  return {
    version,
    keyId: bytes.slice(1, 1 + KEY_ID_BYTES),
    iv: bytes.slice(1 + KEY_ID_BYTES, HEADER_BYTES),
    ciphertext: bytes.slice(HEADER_BYTES),
  };
}

/** Reverse of encode. Throws 'decrypt_failed' on a wrong key or tampered bytes. */
export async function decryptPlanEnvelope(parsed, key) {
  let compressed;
  try {
    compressed = new Uint8Array(
      await crypto.subtle.decrypt({ name: 'AES-GCM', iv: parsed.iv }, key, parsed.ciphertext),
    );
  } catch {
    // GCM authentication failure — wrong key, or the bytes were altered.
    throw new EnvelopeError('decrypt_failed', 'Could not open this plan.');
  }
  try {
    const json = await inflateRaw(compressed);
    return JSON.parse(new TextDecoder().decode(json));
  } catch {
    // Authenticated, so this is a producer bug rather than an attack.
    throw new EnvelopeError('malformed', 'Plan opened but its contents are unreadable.');
  }
}

/** Hex, for display and for matching a device against a Tracker record. */
export const keyIdToHex = (keyId) =>
  Array.from(keyId, (b) => b.toString(16).padStart(2, '0')).join('');
